name: verify-reviewers

on: [pull_request]

jobs:
  reviewers:
    runs-on: [ubuntu-latest]
    steps:
      - name: verify-reviewers
        if: github.event_name == 'pull_request' && github.event.action == 'unassigned'
        run: echo This event is a pull request that had an assignee removed.
   
